name: DesChiffresEtDesLettres
publish_to: 'https://github.com/el2zay/DesChiffresEtDesLettres'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: any
  just_audio_background: ^0.0.1-beta.17
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/